/**
 * A module to implement a rudimentary unit testing system (because I didn't feel like wasting any more time with Jest).
 */

var assertMod = require('./assert');

const SUCCESS = 0;
const FAILURE = 1;
const ERROR = 2;

/**
 * Generates a test to run.
 * 
 * @param {string} label the name of the test to make
 * @param {() => void} test 
 * @returns a function that runs the test, returning a `[status, result]` array, where `status` is `SUCCESS`, `FAILURE`,
 * or `ERROR` and `result` is the error message if status is `FAILURE` or `ERROR` and is `undefined` otherwise.
 */
function makeTest(label, test) {
  "use strict";
  return function() {
    try {
      test();
      return [SUCCESS, undefined];
    } catch (err) {
      if (err instanceof assertMod.AssertFailure) {
        return [FAILURE, "Test '" + label + "' failed: " + err.stack];
      }
      return [ERROR, "Error while running test '" + label + "': " + err.stack];
    }
  }
}

/**
 * Generates and returns a function to run a suite of tests using the provided label and suite of tests.
 * 
 * @param {string} label the label to use when identifying the test
 * @param {(() => void)[]} suite the suite of tests to run (which are functions generated by `makeTest`)
 * @returns a function to call that will run the test suite
 */
function makeTestSuite(label, suite) {
  "use strict";
  // Returns a function to call.
  return function() {
    var testSummary = "";
    var successes = 0;
    var failures = 0;
    var errors = 0;
    var failureMessages = [];  // Includes both failures and errors.
    // Report the name of the suite.
    console.log("Running suite '" + label + "'");
    // Run through each test, checking for exceptions and failures and counting them.
    suite.forEach(test => {
      var [status, result] = test();
      
      // Record the result of each test.
      switch (status) {
        // Dot = success, F = failure, E = error
        case SUCCESS:
          successes++;
          testSummary += ".";
          break;
        case FAILURE:
          failures++;
          testSummary += "F";
          failureMessages.push(result);
          break;
        case ERROR:
          errors++;
          testSummary += "E";
          failureMessages.push(result);
          break;
      }
    });
    
    // Show results
    console.log(testSummary);
    
    // Show failures
    failureMessages.forEach(msg => console.log(msg));
    
    // Show summary.
    console.log("Successes: " + successes + ", failures: " + failures + ", errors: " + errors);
  }
}

/**
 * Runs a list of test suites.
 * 
 * @param {(() => void)[]} suites the list of suites to run
 */
function runTestSuites(suites) {
  suites.forEach(suite => suite());
}

module.exports = {
  makeTest,
  makeTestSuite,
  runTestSuites
}